# Generated by Django 4.2.5 on 2023-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_energy_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySlabRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_usage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_usage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
