# Generated by Django 4.2.5 on 2023-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_energyslabrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='machine',
            field=models.CharField(default='machine1', max_length=20),
        ),
        migrations.AlterField(
            model_name='energyslabrate',
            name='end_usage',
            field=models.DecimalField(decimal_places=2, default=float("inf"), max_digits=10),
        ),
    ]
