# Generated by Django 4.2.5 on 2023-09-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_energy_machine_alter_energyslabrate_end_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
