# Generated by Django 4.2.5 on 2023-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_energycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyslabrate',
            name='end_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energyslabrate',
            name='rate_per_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyslabrate',
            name='start_usage',
            field=models.FloatField(),
        ),
    ]
